jobs:
  - job: build_test_deploy
    steps:
    
    - task: Maven@3
      displayName: Build
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
       mavenPomFile: 'java/pom.xml'
       options: -s java/settings.xml -DnexusUsername=$(mtn_nexus_username) -DnexusPassword=$(mtn_nexus_password) clean install
       mavenOptions: '-Xmx3072m'
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.11'
       jdkArchitectureOption: 'x64'

    - task: Maven@3
      displayName: Build and deploy artifacts to nexus
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
       mavenPomFile: 'java/pom.xml'
       options: -s java/settings.xml -DnexusUsername=$(mtn_nexus_username) -DnexusPassword=$(mtn_nexus_password) clean deploy
       mavenOptions: '-Xmx3072m'
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.11'
       jdkArchitectureOption: 'x64'
